export const GET_TASK_DETAIL_SAGA = 'GET_TASK_DETAIL_SAGA';
export const GET_TASK_DETAIL = 'GET_TASK_DETAIL';


export const CHANGE_TASK_MODAL = 'CHANGE_TASK_MODAL';
export const CHANGE_ASSIGNESS = 'CHANGE_ASSIGNESS';
export const REMOVE_USER_ASSIGN = 'REMOVE_USER_ASSIGN'

export const UPDATE_STATUS_TASK_SAGA = 'UPDATE_STATUS_TASK_SAGA';


export const UPDATE_TASK_SAGA = 'UPDATE_TASK_SAGA';
export const HANDLE_CHANGE_POST_API_SAGA = 'HANDLE_CHANGE_POST_API_SAGA';